<a href="https://colab.research.google.com/github/Aishaamalik/Data-Analysis-Intern/blob/main/Week_0(Geeks_for_Greeks).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Analysis with Python

#Section 1: What is NumPy?

Key Concepts:

- NumPy is a library in Python used for numerical and scientific computing.

- It provides a high-performance multidimensional array object and functions to work with it efficiently.

- The core object in NumPy is called a ndarray (n-dimensional array).

Why NumPy?

- More efficient than Python lists (speed and memory).

- Useful for data analysis, machine learning, simulations, statistics, and more.

#Section 2: Creating NumPy Arrays

##2.1. Using np.empty()

Creates an array without initializing its entries (values are random garbage from memory).

In [1]:
import numpy as np

a = np.empty([2, 2], dtype=int)
print("Matrix a:\n", a)

b = np.empty(2, dtype=int)
print("Matrix b:\n", b)


Matrix a:
 [[        565120508                 0]
 [   18000284026724 28147497671065600]]
Matrix b:
 [              1 140732475047936]


##2.2. Using np.zeros()
Creates an array filled with zeros.

In [2]:
a = np.zeros([2, 2], dtype=int)
print("Matrix a:\n", a)

b = np.zeros(2, dtype=int)
print("Matrix b:\n", b)

c = np.zeros([3, 3])
print("Matrix c:\n", c)


Matrix a:
 [[0 0]
 [0 0]]
Matrix b:
 [0 0]
Matrix c:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
