<a href="https://colab.research.google.com/github/Aishaamalik/Data-Analysis-Intern/blob/main/Week_0(Geeks_for_Greeks).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Analysis with Python

#Section 1: What is NumPy?

Key Concepts:

- NumPy is a library in Python used for numerical and scientific computing.

- It provides a high-performance multidimensional array object and functions to work with it efficiently.

- The core object in NumPy is called a ndarray (n-dimensional array).

Why NumPy?

- More efficient than Python lists (speed and memory).

- Useful for data analysis, machine learning, simulations, statistics, and more.

#Section 2: Creating NumPy Arrays

##2.1. Using np.empty()

Creates an array without initializing its entries (values are random garbage from memory).

In [1]:
import numpy as np

a = np.empty([2, 2], dtype=int)
print("Matrix a:\n", a)

b = np.empty(2, dtype=int)
print("Matrix b:\n", b)


Matrix a:
 [[        565120508                 0]
 [   18000284026724 28147497671065600]]
Matrix b:
 [              1 140732475047936]


##2.2. Using np.zeros()
Creates an array filled with zeros.

In [2]:
a = np.zeros([2, 2], dtype=int)
print("Matrix a:\n", a)

b = np.zeros(2, dtype=int)
print("Matrix b:\n", b)

c = np.zeros([3, 3])
print("Matrix c:\n", c)


Matrix a:
 [[0 0]
 [0 0]]
Matrix b:
 [0 0]
Matrix c:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


 #Section 3: Arithmetic Operations

##3.1. Addition

In [3]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

print(a + b)               # Element-wise addition
print(np.add(a, b))        # Same using np.add

# Add 3 arrays
c = np.array([1, 2, 3, 4])
print(a + b + c)
print(np.add(a, b, c))     # np.add with 3 args ignores c!


[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


##3.2. Subtraction, Multiplication, Division

In [4]:
# Subtraction
print(a - b)
print(np.subtract(a, b))

# Multiplication
print(a * b)
print(np.multiply(a, b))

# Division
print(a / b)
print(np.divide(a, b))


[ 3 67  3 70]
[ 3 67  3 70]
[  10  360  130 3000]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


#Section 4: Indexing and Slicing
##4.1. Indexing

In [5]:
a = np.arange(10, 1, -2)
print("a:", a)

newarr = a[np.array([3, 1, 2])]
print("Selected indices:", newarr)


a: [10  8  6  4  2]
Selected indices: [4 8 6]


##4.2. Slicing

In [6]:
a = np.arange(20)
print("a:", a)

print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])


a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


##4.3. Using Ellipsis (...)

In [7]:
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

print(b[..., 1])  # Get second element in innermost dimension


[[ 2  5]
 [ 8 11]]


#Section 5: Broadcasting
**Concept:**

- Allows arithmetic on arrays with different shapes.

- NumPy automatically stretches the smaller array to match the larger one’s shape.

Example: Calories from nutrients

In [8]:
macros = np.array([
    [0.8, 2.9, 3.9],
    [52.4, 23.6, 36.5],
    [55.2, 31.7, 23.9],
    [14.4, 11, 4.9]
])

cal_per_macro = np.array([3, 3, 8])  # Scaling factors

result = macros * cal_per_macro
print(result)


[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


##5.1. Broadcasting Rules

In [9]:
v = np.array([12, 24, 36])
w = np.array([45, 55])

# Reshape v to (3, 1) to make it broadcastable
print(np.reshape(v, (3, 1)) * w)

X = np.array([[12, 22, 33], [45, 55, 66]])

print(X + v)
print((X.T + w).T)
print(X * 2)


[[ 540  660]
 [1080 1320]
 [1620 1980]]
[[ 24  46  69]
 [ 57  79 102]]
[[ 57  67  78]
 [100 110 121]]
[[ 24  44  66]
 [ 90 110 132]]
